import type { LLMProvider } from "../providers/types"
import type { ReportData, WeeklyData } from "./analyze"

// ── Status report — full LLM generation ───────────────────────────────

const STATUS_SYSTEM = `You are a report compiler that produces a Markdown brain health dashboard for engineering teams.
You receive structured JSON data about a codebase's knowledge health and generate a COMPLETE Markdown report.

OUTPUT FORMAT — follow this structure exactly:

# \ud83e\udde0 Brain Health

> Auto-generated by Wiki Forge on every compile. Do not edit manually.
> Last compiled: \`{timestamp}\`

---

## \ud83d\udcca Overview

| | |
|---|---|
| Documentable files | **{n}** |
| Compiled wiki pages | **{n}** |
| With decision context | **{n}** ({n}%) |
| Without decision context | **{n}** ({n}%) |
| Total decisions captured | **{n}** |

---

## \u26a0\ufe0f Knowledge risk map

\`\`\`mermaid
quadrantChart
    title Knowledge risk by module
    x-axis "Low decision coverage" --> "High decision coverage"
    y-axis "Low bus factor" --> "High bus factor"
    quadrant-1 "Safe"
    quadrant-2 "Needs decisions"
    quadrant-3 "Critical risk"
    quadrant-4 "Needs distribution"
    module-name: [x, y]
\`\`\`

(Plot each module. x = decision coverage 0-1, y = bus factor normalized 0-1. Modules with 0 decisions = x: 0.05. Bus factor 1 = low y.)

---

### \ud83d\udea8 Critical risk / \ud83d\udfe1 Moderate risk / \ud83d\udfe2 Low risk

Tables with: | Module | Bus factor | Primary owner | Decisions | Last active |

---

## \u2705 Action items

Blockquotes (> prefix). Be SPECIFIC: name the engineer, the module path, and the exact risk. Include concrete **Action:** steps referencing \`wf onboard\`, \`wf why --deep\`, or pairing sessions.

---

## \ud83d\udc65 Team context map

Mermaid pie chart showing commit distribution + table with: | Engineer | Modules owned (>50%) | Decisions involved | Last active | Status |

---

## \ud83d\udcdd Recent decisions (last 30 days)

Table: | Date | Module | Decision | Source | Author |

---

## \ud83d\udd0d Coverage gaps

Table: | Source | Commits | Issue | Suggested fix |

---

## \ud83d\udc80 Orphaned docs

(Include this section ONLY if ORPHANED DOCS in the input has entries. These are wiki pages whose source files were deleted from the repo — the docs remain but their subject is gone.)

Table: | Doc | Declared sources (now missing) |

---

## \ud83d\udca1 Analysis

2-3 sentences: what's healthy, what's concerning, what needs immediate attention. Be direct.

---

*Generated by [Wiki Forge](https://github.com/thevrus/Wiki-Forge) · Your codebase remembers.*

RULES:
- Use ONLY the data provided. Never invent modules, engineers, or metrics.
- Omit sections that have no data (e.g., skip "Recent decisions" if there are none).
- Make the action items read like a human engineering manager wrote them.
- Relative dates for "Last active" (e.g., "2 days ago", "47 days ago").
- Keep the Mermaid syntax valid. No quotes in quadrantChart data point names.
- Output the complete Markdown document. No preamble, no code fences wrapping the output.`

function serializeReportData(data: ReportData): string {
  const modulesSummary = data.modules.map((m) => ({
    name: m.name,
    sources: m.sources,
    busFactor: m.busFactor,
    primaryOwner: m.primaryOwner,
    authors: m.authors.slice(0, 5),
    totalCommits: m.totalCommits,
    lastActive: m.lastActive || "unknown",
    decisions: m.decisions.length,
    decisionDetails: m.decisions.slice(0, 5).map((d) => ({
      summary: d.summary,
      source: d.source,
      author: d.author,
      date: d.date,
    })),
    risk: m.riskLevel,
  }))

  const teamSummary = data.team.map((t) => ({
    name: t.name,
    commits: t.totalCommits,
    modulesOwned: t.modulesOwned,
    modulesTouched: t.modulesTouched,
    decisions: t.totalDecisions,
    lastActive: t.lastActive,
    status: t.status,
  }))

  return [
    `Generated at: ${data.generatedAt}`,
    "",
    `TOTALS: ${JSON.stringify(data.totals)}`,
    "",
    `MODULES (${data.modules.length}):`,
    JSON.stringify(modulesSummary, null, 2),
    "",
    `TEAM (${data.team.length}):`,
    JSON.stringify(teamSummary, null, 2),
    "",
    `RECENT DECISIONS (${data.recentDecisions.length}):`,
    JSON.stringify(
      data.recentDecisions.slice(0, 15).map((d) => ({
        date: d.date,
        module: d.module,
        summary: d.summary,
        source: d.source,
        author: d.author,
      })),
      null,
      2,
    ),
    "",
    `COVERAGE GAPS (${data.coverageGaps.length}):`,
    JSON.stringify(data.coverageGaps, null, 2),
    "",
    `ORPHANED DOCS (${data.orphanedDocs?.length ?? 0}): docs whose declared sources no longer exist on disk`,
    JSON.stringify(data.orphanedDocs ?? [], null, 2),
    "",
    data.compilationStats
      ? `COMPILATION STATS: ${JSON.stringify(data.compilationStats)}`
      : "",
  ].join("\n")
}

export async function generateStatusWithLLM(
  data: ReportData,
  provider: LLMProvider,
): Promise<string> {
  return provider.generate(serializeReportData(data), STATUS_SYSTEM)
}

// ── Weekly report — full LLM generation ───────────────────────────────

const WEEKLY_SYSTEM = `You are a report compiler that produces a weekly engineering digest in Markdown.
You receive structured JSON data about what a team shipped and generate a COMPLETE Markdown report.

OUTPUT FORMAT — follow this structure:

# \ud83d\udcc5 Weekly report — {date_range}

> Auto-generated by Wiki Forge. Compiled from {n} merged PRs across the repository.

---

## \ud83d\udcca Summary

One paragraph: PRs merged, engineers active, key highlights, concerns.

---

## \ud83d\ude80 What shipped

Group PRs by module. For each module:

### {Module Name}

| PR | What | Author | Decisions |
|----|------|--------|-----------|
| #{n} | title | author | 0 or "N new" |

If a module had no PRs: show "No PRs this week" row.

---

## \ud83d\udc65 Engineering activity

\`\`\`mermaid
xychart-beta
    title "PRs merged by engineer this week"
    x-axis ["Name1", "Name2"]
    y-axis "PRs" 0 --> {max+2}
    bar [n1, n2]
\`\`\`

Table: | Engineer | PRs merged | Decisions authored | Modules touched |

---

## \ud83e\udde0 Knowledge health changes

Table comparing this week vs last week (if previous data available):
| Metric | Last week | This week | Change |

### New alerts / Positive changes
Blockquotes for risks and improvements.

---

## \ud83d\udcdd Decisions captured this week

Numbered list with module and source reference.

---

*Generated by [Wiki Forge](https://github.com/thevrus/Wiki-Forge) · Week {n}, {year}*

RULES:
- Use ONLY the data provided. Never invent PRs, engineers, or metrics.
- Omit sections that have no data.
- The summary should highlight impact: performance numbers, security fixes, conversion metrics when present in PR titles.
- Make it read like a human engineering manager wrote it.
- Valid Mermaid syntax. Only include chart if 2+ engineers have PRs.
- Output the complete Markdown document. No preamble, no code fences wrapping the output.`

function serializeWeeklyData(data: WeeklyData): string {
  const prs = data.prsMerged.map((p) => ({
    number: p.number,
    title: p.title,
    author: p.author,
    module: p.module,
    decisions: p.decisions,
  }))

  const engineers = data.engineerActivity.map((e) => ({
    name: e.name,
    prs: e.prsMerged,
    decisions: e.decisionsAuthored,
    modules: e.modulesTouched,
    newModules: e.newModules,
  }))

  const currentCoverage =
    data.current.totals.compiledPages > 0
      ? Math.round(
          (data.current.totals.withDecisions /
            data.current.totals.compiledPages) *
            100,
        )
      : 0

  const previousCoverage = data.previous
    ? data.previous.totals.compiledPages > 0
      ? Math.round(
          (data.previous.totals.withDecisions /
            data.previous.totals.compiledPages) *
            100,
        )
      : 0
    : null

  const alerts = data.current.modules
    .filter((m) => m.riskLevel === "critical")
    .map((m) => ({
      module: m.sources.join(", "),
      busFactor: m.busFactor,
      owner: m.primaryOwner?.name,
      ownerPercentage: m.primaryOwner?.percentage,
      lastActive: m.lastActive,
      decisions: m.decisions.length,
    }))

  // Detect bus factor improvements
  const improvements: Array<{ module: string; from: number; to: number }> = []
  if (data.previous) {
    for (const mod of data.current.modules) {
      const prev = data.previous.modules.find((m) => m.docPath === mod.docPath)
      if (prev && mod.busFactor > prev.busFactor) {
        improvements.push({
          module: mod.sources.join(", "),
          from: prev.busFactor,
          to: mod.busFactor,
        })
      }
    }
  }

  const weekDecisions = data.current.recentDecisions.filter(
    (d) => d.date >= data.period.start && d.date <= data.period.end,
  )

  return [
    `PERIOD: ${data.period.start} to ${data.period.end} (Week ${data.period.weekNumber}, ${data.period.year})`,
    "",
    `PRS MERGED (${prs.length}):`,
    JSON.stringify(prs, null, 2),
    "",
    `ENGINEER ACTIVITY (${engineers.length}):`,
    JSON.stringify(engineers, null, 2),
    "",
    `INACTIVE TEAM MEMBERS:`,
    JSON.stringify(
      data.current.team
        .filter(
          (t) =>
            t.status === "inactive" &&
            !engineers.some((e) => e.name === t.name),
        )
        .map((t) => ({ name: t.name, lastActive: t.lastActive })),
      null,
      2,
    ),
    "",
    `KNOWLEDGE HEALTH:`,
    `  Current decision coverage: ${currentCoverage}%`,
    previousCoverage !== null
      ? `  Previous decision coverage: ${previousCoverage}%`
      : "  No previous data for comparison",
    `  Current total decisions: ${data.current.totals.totalDecisions}`,
    data.previous
      ? `  Previous total decisions: ${data.previous.totals.totalDecisions}`
      : "",
    `  Critical risk modules: ${data.current.modules.filter((m) => m.riskLevel === "critical").length}`,
    data.previous
      ? `  Previous critical risk modules: ${data.previous.modules.filter((m) => m.riskLevel === "critical").length}`
      : "",
    `  Coverage gaps: ${data.current.coverageGaps.length}`,
    "",
    `RISK ALERTS:`,
    JSON.stringify(alerts, null, 2),
    "",
    `BUS FACTOR IMPROVEMENTS:`,
    JSON.stringify(improvements, null, 2),
    "",
    `DECISIONS CAPTURED THIS WEEK (${weekDecisions.length}):`,
    JSON.stringify(
      weekDecisions.map((d) => ({
        summary: d.summary,
        module: d.module,
        source: d.source,
      })),
      null,
      2,
    ),
  ].join("\n")
}

export async function generateWeeklyWithLLM(
  data: WeeklyData,
  provider: LLMProvider,
): Promise<string> {
  return provider.generate(serializeWeeklyData(data), WEEKLY_SYSTEM)
}
