import { writeFileSync } from "node:fs"
import { join } from "node:path"
import type { LLMProvider } from "../providers/types"
import { validateStatusReport } from "../validation/report"
import { daysSince, type ModuleAnalysis, type ReportData } from "./analyze"
import { generateStatusWithLLM } from "./narrate"

const MAX_ATTEMPTS = 2

export async function generateStatusReport(
  docsDir: string,
  data: ReportData,
  provider?: LLMProvider,
): Promise<string> {
  const outputPath = join(docsDir, "_status.md")

  // Primary path: LLM generates the full report
  if (provider) {
    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      try {
        const raw = await generateStatusWithLLM(data, provider)
        const validation = validateStatusReport(raw, data)
        if (validation.valid) {
          writeFileSync(outputPath, `${validation.cleaned}\n`)
          return outputPath
        }
        // Last attempt — use cleaned output even with warnings
        if (attempt === MAX_ATTEMPTS) {
          writeFileSync(outputPath, `${validation.cleaned}\n`)
          return outputPath
        }
      } catch {
        // Fall through to template on error
        break
      }
    }
  }

  // Fallback: deterministic template (no LLM required)
  const content = renderTemplate(data)
  writeFileSync(outputPath, content)
  return outputPath
}

// ── Template fallback ─────────────────────────────────────────────────

function renderTemplate(data: ReportData): string {
  const lines: string[] = []
  const {
    totals,
    modules,
    team,
    recentDecisions,
    coverageGaps,
    orphanedDocs,
    compilationStats,
  } = data
  const decisionCoverage =
    totals.compiledPages > 0
      ? Math.round((totals.withDecisions / totals.compiledPages) * 100)
      : 0

  lines.push("# \ud83e\udde0 Brain Health")
  lines.push("")
  lines.push(
    "> Auto-generated by Wiki Forge on every compile. Do not edit manually.",
  )
  lines.push(`> Last compiled: \`${data.generatedAt}\``)
  lines.push("")
  lines.push("---")
  lines.push("")

  // Overview
  lines.push("## \ud83d\udcca Overview")
  lines.push("")
  lines.push("| | |")
  lines.push("|---|---|")
  lines.push(`| Documentable files | **${totals.documentableFiles}** |`)
  lines.push(`| Compiled wiki pages | **${totals.compiledPages}** |`)
  lines.push(
    `| With decision context | **${totals.withDecisions}** (${decisionCoverage}%) |`,
  )
  lines.push(
    `| Without decision context | **${totals.withoutDecisions}** (${100 - decisionCoverage}%) |`,
  )
  lines.push(`| Total decisions captured | **${totals.totalDecisions}** |`)
  if (totals.incidentsReferenced > 0)
    lines.push(`| Incidents referenced | **${totals.incidentsReferenced}** |`)
  if (totals.adrsLinked > 0)
    lines.push(`| ADRs linked | **${totals.adrsLinked}** |`)
  lines.push("")
  lines.push("---")
  lines.push("")

  // Knowledge risk map
  if (modules.length >= 2) {
    lines.push("## \u26a0\ufe0f Knowledge risk map")
    lines.push("")
    lines.push("```mermaid")
    lines.push("quadrantChart")
    lines.push("    title Knowledge risk by module")
    lines.push(
      '    x-axis "Low decision coverage" --> "High decision coverage"',
    )
    lines.push('    y-axis "Low bus factor" --> "High bus factor"')
    lines.push('    quadrant-1 "Safe"')
    lines.push('    quadrant-2 "Needs decisions"')
    lines.push('    quadrant-3 "Critical risk"')
    lines.push('    quadrant-4 "Needs distribution"')

    const maxBusFactor = Math.max(...modules.map((m) => m.busFactor), 1)
    for (const mod of modules) {
      const x =
        mod.decisions.length > 0
          ? Math.min(mod.decisions.length / 5, 1) * 0.8 + 0.15
          : 0.05
      const y =
        maxBusFactor > 0
          ? (mod.busFactor / (maxBusFactor + 1)) * 0.8 + 0.1
          : 0.1
      const slug = mod.name
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/-+$/, "")
      lines.push(`    ${slug}: [${x.toFixed(2)}, ${y.toFixed(2)}]`)
    }
    lines.push("```")
    lines.push("")
    lines.push("---")
    lines.push("")
  }

  // Risk tables
  const critical = modules.filter((m) => m.riskLevel === "critical")
  const moderate = modules.filter((m) => m.riskLevel === "moderate")
  const low = modules.filter((m) => m.riskLevel === "low")

  if (critical.length > 0) {
    lines.push("### \ud83d\udea8 Critical risk")
    lines.push("")
    lines.push(...riskTable(critical))
    lines.push("")
  }
  if (moderate.length > 0) {
    lines.push("### \ud83d\udfe1 Moderate risk")
    lines.push("")
    lines.push(...riskTable(moderate))
    lines.push("")
  }
  if (low.length > 0) {
    lines.push("### \ud83d\udfe2 Low risk")
    lines.push("")
    lines.push(...riskTable(low))
    lines.push("")
  }

  // Action items
  const actions = generateActions(modules)
  if (actions.length > 0) {
    lines.push("---")
    lines.push("")
    lines.push("## \u2705 Action items")
    lines.push("")
    for (const action of actions) {
      lines.push(`> ${action}`)
      lines.push("")
    }
  }

  // Team context map
  if (team.length > 0) {
    lines.push("---")
    lines.push("")
    lines.push("## \ud83d\udc65 Team context map")
    lines.push("")
    lines.push("```mermaid")
    lines.push("pie title Context distribution across team")
    for (const member of team.slice(0, 10)) {
      lines.push(`    "${member.name}" : ${member.totalCommits}`)
    }
    lines.push("```")
    lines.push("")
    lines.push(
      "| Engineer | Modules owned (>50%) | Decisions involved | Last active | Status |",
    )
    lines.push(
      "|----------|---------------------|:-----------------:|-------------|--------|",
    )
    for (const member of team) {
      const owned =
        member.modulesOwned.length > 0
          ? member.modulesOwned.map((m) => `\`${m.toLowerCase()}\``).join(", ")
          : "— (distributed)"
      const statusIcon = member.status === "active" ? "Active" : "Inactive"
      lines.push(
        `| ${member.name} | ${owned} | ${member.totalDecisions} | ${formatRelativeDate(member.lastActive)} | ${statusIcon} |`,
      )
    }
    lines.push("")
  }

  // Recent decisions
  if (recentDecisions.length > 0) {
    lines.push("---")
    lines.push("")
    lines.push("## \ud83d\udcdd Recent decisions (last 30 days)")
    lines.push("")
    lines.push("| Date | Module | Decision | Source | Author |")
    lines.push("|------|--------|----------|--------|--------|")
    for (const d of recentDecisions.slice(0, 15)) {
      lines.push(
        `| ${d.date} | \`${d.module.toLowerCase()}\` | ${d.summary} | ${d.source} | ${d.author || "—"} |`,
      )
    }
    lines.push("")
  }

  // Coverage gaps
  if (coverageGaps.length > 0) {
    lines.push("---")
    lines.push("")
    lines.push("## \ud83d\udd0d Coverage gaps")
    lines.push("")
    lines.push("| Source | Commits | Issue | Suggested fix |")
    lines.push("|------|:-------:|-------|---------------|")
    for (const gap of coverageGaps) {
      lines.push(
        `| \`${gap.file}\` | ${gap.commits} | ${gap.issue} | ${gap.suggestedFix} |`,
      )
    }
    lines.push("")
  }

  // Orphaned docs — sources deleted from the repo, doc still on disk
  if (orphanedDocs && orphanedDocs.length > 0) {
    lines.push("---")
    lines.push("")
    lines.push("## \ud83d\udc80 Orphaned docs")
    lines.push("")
    lines.push(
      "These pages document source files that no longer exist in the repo. Either restore the sources, update the doc map, or delete the docs.",
    )
    lines.push("")
    lines.push("| Doc | Declared sources (now missing) |")
    lines.push("|-----|--------------------------------|")
    for (const o of orphanedDocs) {
      lines.push(
        `| \`${o.docPath}\` | ${o.sources.map((s) => `\`${s}\``).join(", ")} |`,
      )
    }
    lines.push("")
  }

  // Compilation stats
  if (compilationStats) {
    lines.push("---")
    lines.push("")
    lines.push("## \u2699\ufe0f Compilation stats")
    lines.push("")
    lines.push("| Metric | Value |")
    lines.push("|--------|-------|")
    lines.push(`| Total compiles to date | ${compilationStats.totalCompiles} |`)
    if (compilationStats.averageCost !== "—") {
      lines.push(
        `| Average cost per compile | ${compilationStats.averageCost} |`,
      )
      lines.push(`| Total spent (all time) | ${compilationStats.totalCost} |`)
    }
    lines.push("")
  }

  lines.push("---")
  lines.push("")
  lines.push(
    "*Generated by [Wiki Forge](https://github.com/thevrus/Wiki-Forge) · Your codebase remembers.*",
  )
  lines.push("")

  return lines.join("\n")
}

// ── Helpers ───────────────────────────────────────────────────────────

function riskTable(modules: ModuleAnalysis[]): string[] {
  const lines: string[] = []
  lines.push(
    "| Module | Bus factor | Primary owner | Decisions | Last active |",
  )
  lines.push("|--------|:---------:|---------------|:---------:|-------------|")
  for (const mod of modules) {
    const owner = mod.primaryOwner
      ? `${mod.primaryOwner.name} (${mod.primaryOwner.percentage}%)`
      : "—"
    lines.push(
      `| \`${mod.sources.join(", ")}\` | **${mod.busFactor}** | ${owner} | ${mod.decisions.length} | ${formatRelativeDate(mod.lastActive)} |`,
    )
  }
  return lines
}

function generateActions(modules: ModuleAnalysis[]): string[] {
  const actions: string[] = []

  for (const mod of modules) {
    if (mod.riskLevel !== "critical") continue
    const parts: string[] = [`**${mod.sources.join(", ")}**`]

    if (mod.busFactor <= 1 && mod.primaryOwner) {
      parts.push("Bus factor 1.")
      const inactive = daysSince(mod.lastActive)
      if (inactive > 30) {
        parts.push(
          `${mod.primaryOwner.name} hasn't committed in ${inactive} days. This is a high knowledge risk.`,
        )
        parts.push(
          `**Action:** Schedule a pairing session or run \`wf onboard @teammate --modules ${mod.name.toLowerCase()}\` to create a knowledge transfer path.`,
        )
      } else {
        parts.push(
          `${mod.primaryOwner.name} holds ${mod.primaryOwner.percentage}% of context.`,
        )
        parts.push(
          `**Action:** Assign the next task to a second engineer with ${mod.primaryOwner.name} reviewing.`,
        )
      }
    }

    if (mod.decisions.length === 0) {
      parts.push("Decision coverage: 0%.")
      parts.push(
        `**Action:** Run \`wf why --deep ${mod.sources[0]}\` to attempt inference from commit messages.`,
      )
    }

    actions.push(parts.join(" "))
  }

  for (const mod of modules) {
    if (mod.riskLevel !== "moderate") continue
    if (mod.busFactor <= 1 && mod.primaryOwner) {
      actions.push(
        `**${mod.sources.join(", ")}** — Bus factor 1. ${mod.primaryOwner.name} holds ${mod.primaryOwner.percentage}% of context. **Action:** Assign the next task to a second engineer.`,
      )
    } else if (mod.decisions.length === 0) {
      actions.push(
        `**${mod.sources.join(", ")}** — 0% decision coverage. **Action:** Run \`wf why --deep ${mod.sources[0]}\`.`,
      )
    }
  }

  return actions
}

function formatRelativeDate(dateStr: string): string {
  if (!dateStr) return "—"
  const days = daysSince(dateStr)
  if (days === 0) return "today"
  if (days === 1) return "1 day ago"
  if (days < 7) return `${days} days ago`
  if (days < 30) {
    const weeks = Math.floor(days / 7)
    return weeks === 1 ? "1 week ago" : `${weeks} weeks ago`
  }
  if (days < 365) {
    const months = Math.floor(days / 30)
    return months === 1 ? "1 month ago" : `${months} months ago`
  }
  return dateStr
}
