import { mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type { LLMProvider } from "../providers/types"
import { validateWeeklyReport } from "../validation/report"
import { daysSince, type WeeklyData } from "./analyze"
import { generateWeeklyWithLLM } from "./narrate"

const MAX_ATTEMPTS = 2

export async function generateWeeklyReport(
  docsDir: string,
  data: WeeklyData,
  provider?: LLMProvider,
): Promise<string> {
  const { period } = data
  const weekLabel = `${period.year}-w${String(period.weekNumber).padStart(2, "0")}`
  const reportsDir = join(docsDir, "_reports")
  mkdirSync(reportsDir, { recursive: true })
  const outputPath = join(reportsDir, `${weekLabel}.md`)

  // Primary path: LLM generates the full report
  if (provider) {
    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      try {
        const raw = await generateWeeklyWithLLM(data, provider)
        const validation = validateWeeklyReport(raw, data)
        if (validation.valid || attempt === MAX_ATTEMPTS) {
          writeFileSync(outputPath, `${validation.cleaned}\n`)
          savePreviousStatus(reportsDir, data)
          return outputPath
        }
      } catch {
        break
      }
    }
  }

  // Fallback: deterministic template
  const content = renderTemplate(data)
  writeFileSync(outputPath, content)
  savePreviousStatus(reportsDir, data)
  return outputPath
}

function savePreviousStatus(reportsDir: string, data: WeeklyData): void {
  writeFileSync(
    join(reportsDir, ".previous-status.json"),
    JSON.stringify(data.current, null, 2),
  )
}

// ── Template fallback ─────────────────────────────────────────────────

function renderTemplate(data: WeeklyData): string {
  const { period, prsMerged, engineerActivity, current, previous } = data
  const lines: string[] = []

  const dateRange = `${formatDate(period.start)}–${formatDate(period.end)}`

  lines.push(`# \ud83d\udcc5 Weekly report — ${dateRange}`)
  lines.push("")
  lines.push(
    `> Auto-generated by Wiki Forge. Compiled from ${prsMerged.length} merged PRs across the repository.`,
  )
  lines.push("")
  lines.push("---")
  lines.push("")

  // Summary
  lines.push("## \ud83d\udcca Summary")
  lines.push("")
  const activeEngineers = engineerActivity.filter((e) => e.prsMerged > 0).length
  const newDecisions = current.recentDecisions.filter(
    (d) => d.date >= period.start && d.date <= period.end,
  ).length
  const currentCoverage =
    current.totals.compiledPages > 0
      ? Math.round(
          (current.totals.withDecisions / current.totals.compiledPages) * 100,
        )
      : 0
  const prevCoverage = previous
    ? previous.totals.compiledPages > 0
      ? Math.round(
          (previous.totals.withDecisions / previous.totals.compiledPages) * 100,
        )
      : 0
    : null
  const coverageDelta =
    prevCoverage !== null
      ? `${prevCoverage}% → ${currentCoverage}%`
      : `${currentCoverage}%`

  lines.push(
    `${prsMerged.length} PRs merged by ${activeEngineers} engineers. ` +
      `${newDecisions} new decisions captured. ` +
      `Decision coverage: ${coverageDelta}.`,
  )
  lines.push("")
  lines.push("---")
  lines.push("")

  // What shipped
  lines.push("## \ud83d\ude80 What shipped")
  lines.push("")

  const byModule = new Map<string, typeof prsMerged>()
  for (const pr of prsMerged) {
    const existing = byModule.get(pr.module)
    if (existing) existing.push(pr)
    else byModule.set(pr.module, [pr])
  }

  const moduleOrder = [...byModule.keys()].sort((a, b) => {
    if (a === "other") return 1
    if (b === "other") return -1
    return a.localeCompare(b)
  })

  for (const moduleName of moduleOrder) {
    const modulePrs = byModule.get(moduleName)!
    lines.push(`### ${moduleName}`)
    lines.push("")
    lines.push("| PR | What | Author | Decisions |")
    lines.push("|----|------|--------|-----------|")
    for (const pr of modulePrs) {
      const decStr = pr.decisions > 0 ? `${pr.decisions} new` : "0"
      lines.push(`| #${pr.number} | ${pr.title} | ${pr.author} | ${decStr} |`)
    }
    lines.push("")
  }

  // Quiet modules
  const modulesWithPRs = new Set(byModule.keys())
  const quietModules = current.modules
    .filter((m) => !modulesWithPRs.has(m.name) && m.name !== "other")
    .map((m) => m.name)
  if (quietModules.length > 0 && quietModules.length <= 5) {
    for (const mod of quietModules) {
      lines.push(`### ${mod}`)
      lines.push("")
      lines.push("| PR | What | Author | Decisions |")
      lines.push("|----|------|--------|-----------|")
      lines.push("| — | No PRs this week | | |")
      lines.push("")
    }
  }

  lines.push("---")
  lines.push("")

  // Engineering activity
  if (engineerActivity.length > 0) {
    lines.push("## \ud83d\udc65 Engineering activity")
    lines.push("")

    const activeOnly = engineerActivity.filter((e) => e.prsMerged > 0)
    if (activeOnly.length >= 2) {
      const maxPrs = Math.max(...activeOnly.map((e) => e.prsMerged))
      lines.push("```mermaid")
      lines.push("xychart-beta")
      lines.push('    title "PRs merged by engineer this week"')
      lines.push(
        `    x-axis [${activeOnly.map((e) => `"${e.name}"`).join(", ")}]`,
      )
      lines.push(`    y-axis "PRs" 0 --> ${maxPrs + 2}`)
      lines.push(`    bar [${activeOnly.map((e) => e.prsMerged).join(", ")}]`)
      lines.push("```")
      lines.push("")
    }

    lines.push(
      "| Engineer | PRs merged | Decisions authored | Modules touched |",
    )
    lines.push("|----------|:---------:|:-----------------:|----------------|")
    for (const eng of engineerActivity) {
      const modules =
        eng.modulesTouched.length > 0
          ? eng.modulesTouched.map((m) => m.toLowerCase()).join(", ")
          : "—"
      lines.push(
        `| ${eng.name} | ${eng.prsMerged} | ${eng.decisionsAuthored} | ${modules} |`,
      )
    }
    lines.push("")

    const activeNames = new Set(engineerActivity.map((e) => e.name))
    const inactive = current.team.filter((t) => !activeNames.has(t.name))
    for (const member of inactive) {
      lines.push(`| ${member.name} | 0 | 0 | — |`)
    }
    if (inactive.length > 0) lines.push("")

    lines.push("---")
    lines.push("")
  }

  // Knowledge health changes
  lines.push("## \ud83e\udde0 Knowledge health changes")
  lines.push("")

  if (previous) {
    const prevDecCov =
      previous.totals.compiledPages > 0
        ? Math.round(
            (previous.totals.withDecisions / previous.totals.compiledPages) *
              100,
          )
        : 0
    const avgBusPrev =
      previous.modules.length > 0
        ? previous.modules.reduce((s, m) => s + m.busFactor, 0) /
          previous.modules.length
        : 0
    const avgBusCurr =
      current.modules.length > 0
        ? current.modules.reduce((s, m) => s + m.busFactor, 0) /
          current.modules.length
        : 0
    const critPrev = previous.modules.filter(
      (m) => m.riskLevel === "critical",
    ).length
    const critCurr = current.modules.filter(
      (m) => m.riskLevel === "critical",
    ).length

    lines.push("| Metric | Last week | This week | Change |")
    lines.push("|--------|:---------:|:---------:|:------:|")
    lines.push(
      `| Decision coverage | ${prevDecCov}% | ${currentCoverage}% | ${delta(currentCoverage, prevDecCov, "%")} |`,
    )
    lines.push(
      `| Decisions captured | ${previous.totals.totalDecisions} | ${current.totals.totalDecisions} | ${deltaNum(current.totals.totalDecisions, previous.totals.totalDecisions)} |`,
    )
    lines.push(
      `| Average bus factor | ${avgBusPrev.toFixed(1)} | ${avgBusCurr.toFixed(1)} | ${delta(avgBusCurr, avgBusPrev)} |`,
    )
    lines.push(
      `| Critical risk modules | ${critPrev} | ${critCurr} | ${deltaNum(critCurr, critPrev)} |`,
    )
    lines.push(
      `| Coverage gaps | ${previous.coverageGaps.length} | ${current.coverageGaps.length} | ${deltaNum(current.coverageGaps.length, previous.coverageGaps.length)} |`,
    )
  } else {
    lines.push("| Metric | This week |")
    lines.push("|--------|:---------:|")
    lines.push(`| Decision coverage | ${currentCoverage}% |`)
    lines.push(`| Decisions captured | ${current.totals.totalDecisions} |`)
    const avgBus =
      current.modules.length > 0
        ? (
            current.modules.reduce((s, m) => s + m.busFactor, 0) /
            current.modules.length
          ).toFixed(1)
        : "0"
    lines.push(`| Average bus factor | ${avgBus} |`)
    lines.push(
      `| Critical risk modules | ${current.modules.filter((m) => m.riskLevel === "critical").length} |`,
    )
    lines.push(`| Coverage gaps | ${current.coverageGaps.length} |`)
    lines.push("")
    lines.push("*No previous week data available for comparison.*")
  }

  lines.push("")

  // Alerts
  const alerts: string[] = []
  const positives: string[] = []

  for (const mod of current.modules) {
    if (mod.riskLevel === "critical" && mod.primaryOwner) {
      const inactive = daysSince(mod.lastActive)
      if (inactive > 30) {
        alerts.push(
          `**\`${mod.sources.join(", ")}\`** became critical risk. ` +
            `${mod.primaryOwner.name} has not committed in ${inactive} days. ` +
            `They are the sole context holder for ${mod.decisions.length} decisions.`,
        )
      }
    }
  }

  if (previous) {
    for (const mod of current.modules) {
      const prev = previous.modules.find((m) => m.docPath === mod.docPath)
      if (prev && mod.busFactor > prev.busFactor) {
        positives.push(
          `**\`${mod.sources.join(", ")}\`** bus factor improved from ${prev.busFactor} → ${mod.busFactor}.`,
        )
      }
    }
  }

  if (alerts.length > 0) {
    lines.push("### New alerts")
    lines.push("")
    for (const a of alerts) {
      lines.push(`> ${a}`)
      lines.push("")
    }
  }

  if (positives.length > 0) {
    lines.push("### Positive changes")
    lines.push("")
    for (const p of positives) {
      lines.push(`> ${p}`)
      lines.push("")
    }
  }

  lines.push("---")
  lines.push("")

  // Decisions this week
  const weekDecisions = current.recentDecisions.filter(
    (d) => d.date >= period.start && d.date <= period.end,
  )
  if (weekDecisions.length > 0) {
    lines.push("## \ud83d\udcdd Decisions captured this week")
    lines.push("")
    for (let i = 0; i < weekDecisions.length; i++) {
      const d = weekDecisions[i]!
      lines.push(
        `${i + 1}. **${d.summary}** (${d.module.toLowerCase()}) — *Source: ${d.source}*`,
      )
      lines.push("")
    }
    lines.push("---")
    lines.push("")
  }

  lines.push(
    `*Generated by [Wiki Forge](https://github.com/thevrus/Wiki-Forge) · Week ${period.weekNumber}, ${period.year}*`,
  )
  lines.push("")

  return lines.join("\n")
}

// ── Helpers ───────────────────────────────────────────────────────────

function formatDate(dateStr: string): string {
  const d = new Date(dateStr)
  return d.toLocaleDateString("en-US", { month: "short", day: "numeric" })
}

function delta(current: number, previous: number, suffix = ""): string {
  const diff = current - previous
  if (diff === 0) return "—"
  const sign = diff > 0 ? "+" : ""
  return `${sign}${Number.isInteger(diff) ? diff : diff.toFixed(1)}${suffix}`
}

function deltaNum(current: number, previous: number): string {
  const diff = current - previous
  if (diff === 0) return "—"
  const sign = diff > 0 ? "+" : ""
  return `${sign}${diff}`
}
